Repository bringyourownideas/silverstripe-maintenance, pull requests merged in 2018-05, with the labels that each got.

#45 Add name to config block and rename to jobs.yml
  _config/jobs.yml
Labels: affects/v3, change/patch

#44 Add ComposerLoader class, PSR-4 autoloader and branch alias
  .travis.yml
  composer.json
  phpcs.xml.dist
  src/Admin/MaintenanceAdmin.php
  src/Model/ScheduledRun.php
  src/Util/ComposerLoader.php
  tests/.gitkeep
  tests/Admin/MaintenanceAdminTest.php
  tests/Util/ComposerLoaderTest.php
Labels: affects/v3, change/minor

#48 MINOR Refactor scheduled execution logic and provide a getter for job instance
  src/Model/ScheduledRun.php
Labels: affects/v3, change/minor

#49 Pulls/1.0/refactor
  composer.json
  css/sitesummary.css
  src/Admin/MaintenanceAdmin.php
  src/Model/Package.php
  src/Reports/SiteSummary.php
  src/Tasks/UpdatePackageInfo.php
  templates/Package_summary.ss
  tests/Admin/MaintenanceAdminTest.php
  tests/Model/PackageTest.php
  tests/Reports/Package.yml
  tests/Reports/SiteSummaryTest.php
  tests/Tasks/UpdatePackageInfoTest.php
Labels: affects/v3, change/major

#51 NEW Make ComposerLoader extensible
  .travis.yml
  composer.json
  src/Util/ComposerLoader.php
Labels: affects/v4, change/minor

#50 Add button on gridfield that links to addons
  css/sitesummary.css
  src/Forms/GridFieldLinkButton.php
  src/Reports/SiteSummary.php
  templates/GridFieldLinkButton.ss
Labels: affects/v3, change/minor

#58 Open link in new window
  templates/GridFieldLinkButton.ss
Labels: affects/v3, change/patch

#59 Excluding themes from Site Summary report
  src/Reports/SiteSummary.php
  src/Tasks/UpdatePackageInfo.php
Labels: affects/v4, change/patch

#54 FIX Include require-dev in modules list when building models
  src/Tasks/UpdatePackageInfo.php
Labels: affects/v3, change/patch

#56 FIX Ensure report columns can be extended
  src/Model/Package.php
  src/Reports/SiteSummary.php
  tests/Tasks/UpdatePackageInfoTest.php
Labels: affects/v3, change/patch

#55 NEW Showing framework/CMS version on module report
  css/sitesummary.css
  src/Forms/GridFieldHtmlFragment.php
  src/Reports/SiteSummary.php
  templates/SiteSummary_VersionHeader.ss
Labels: affects/v3, change/minor

#66 Renaming the UpdatePackageInfo task
  src/Model/Package.php
  src/Reports/SiteSummary.php
  src/Tasks/UpdatePackageInfoTask.php
  tests/Tasks/UpdatePackageInfoTest.php
Labels: affects/v3, change/major

#69 Updating table summary column to be clickable with a link to addons
  css/sitesummary.css
  src/Reports/SiteSummary.php
  templates/Package_summary.ss
Labels: affects/v3, change/minor

#65 Introduce a queued job to fetch updates and button to trigger it
  _config/jobs.yml
  composer.json
  css/sitesummary.css
  javascript/CheckForUpdates.js
  src/Forms/GridFieldRefreshButton.php
  src/Jobs/CheckForUpdatesJob.php
  src/Model/ScheduledRun.php
  src/Reports/SiteSummary.php
  templates/GridFieldRefreshButton.ss
  tests/Forms/GridFieldLinkButtonTest.php
  tests/Forms/GridFieldRefreshButtonTest.php
  tests/Forms/GridFieldRefreshButtonTest.yml
Labels: affects/v3, change/major

#73 Adding version header to API calls and introducing caching
  src/Util/SupportedAddonsLoader.php
  tests/Util/SupportedAddonsLoaderTest.php
Labels: affects/v4, change/minor

#72 support security (and other) alerts
  .editorconfig
  css/sitesummary.css
  javascript/CheckForUpdates.js
  src/Forms/GridFieldHtmlFragment.php
  src/Forms/GridFieldLinkButton.php
  src/Forms/GridFieldRefreshButton.php
  src/Model/Package.php
  src/Reports/SiteSummary.php
  templates/Package_summary.ss
  tests/Forms/GridFieldLinkButtonTest.php
  tests/Forms/GridFieldRefreshButtonTest.php
  tests/Model/PackageTest.php
  tests/Reports/SiteSummaryTest.php
  tests/Reports/Stubs/SiteSummaryExtensionStub.php
Labels: affects/v4, change/major

#74 FIX pass correct parameter to badges extension hook
  src/Model/Package.php
  tests/Model/PackageTest.php
Labels: affects/v4, change/patch

#76 API Implement namespace for GridFieldDropdownFilter
  src/Forms/GridFieldDropdownFilter.php
  src/Forms/GridFieldHtmlFragment.php
  src/Forms/GridFieldLinkButton.php
  src/Jobs/CheckForUpdatesJob.php
  src/Model/Package.php
  src/Reports/SiteSummary.php
Labels: affects/v3, change/major

#75 FIX Serialize data before saving to cache, and make job description more descriptive
  src/Jobs/CheckForUpdatesJob.php
  src/Util/SupportedAddonsLoader.php
  tests/Util/SupportedAddonsLoaderTest.php
Labels: affects/v3, change/patch

#77 FIX Use Injector to create tasks in tests, ensures extensions can run with dependency injection
  tests/Tasks/UpdatePackageInfoTest.php
Labels: affects/v3, change/patch

#78 NEW Upgrading to SS4
  .scrutinizer.yml
  .travis.yml
  .upgrade.yml
  _config/cache.yml
  composer.json
  css/sitesummary.css
  javascript/GridfieldDropdownFilter.js
  src/Forms/GridFieldDropdownFilter.php
  src/Forms/GridFieldHtmlFragment.php
  src/Forms/GridFieldLinkButton.php
  src/Forms/GridFieldRefreshButton.php
  src/Jobs/CheckForUpdatesJob.php
  src/Model/Package.php
  src/Reports/SiteSummary.php
  src/Tasks/UpdatePackageInfoTask.php
  src/Util/ComposerLoader.php
  src/Util/SupportedAddonsLoader.php
  templates/BringYourOwnIdeas/Maintenance/Forms/GridFieldDropdownFilter.ss
  templates/BringYourOwnIdeas/Maintenance/Forms/GridFieldLinkButton.ss
  templates/BringYourOwnIdeas/Maintenance/Forms/GridFieldRefreshButton.ss
  templates/GridFieldLinkButton.ss
  templates/GridFieldRefreshButton.ss
  tests/Forms/GridFieldLinkButtonTest.php
  tests/Forms/GridFieldRefreshButtonTest.php
  tests/Forms/GridFieldRefreshButtonTest.yml
  tests/Model/PackageTest.php
  tests/Reports/SiteSummaryTest.php
  tests/Tasks/UpdatePackageInfoTest.php
  tests/Util/ComposerLoaderTest.php
  tests/Util/Fixtures/composer.json
  tests/Util/Fixtures/composer.lock
  tests/Util/SupportedAddonsLoaderTest.php
Labels: affects/v4, change/major

#86 NEW Add information link for maintenance module to the report
  css/sitesummary.css
  src/Reports/SiteSummary.php
  templates/BringYourOwnIdeas/Maintenance/Reports/SiteSummary/MoreInformationLink.ss
Labels: affects/v4, change/minor

#82 NEW Convert module to a vendor module
  _config.php
  composer.json
  src/Forms/GridFieldDropdownFilter.php
Labels: affects/v4, change/minor

#83 FIX Update namespaces in translations and run text collector
  lang/_manifest_exclude
  lang/en.yml
  src/Forms/GridFieldRefreshButton.php
  src/Jobs/CheckForUpdatesJob.php
  templates/Package_summary.ss
Labels: affects/v4, change/patch

#84 FIX Make update button primary, add icon (SS 4.2+) for explore addons, reorder buttons
  src/Forms/GridFieldRefreshButton.php
  src/Reports/SiteSummary.php
  templates/BringYourOwnIdeas/Maintenance/Forms/GridFieldLinkButton.ss
Labels: affects/v4, change/patch, type/UX

#85 NEW Convert frontend assets to use silverstripe/webpack-config
  .editorconfig
  .eslintignore
  .eslintrc.js
  .gitattributes
  .gitignore
  .sass-lint.yml
  client/dist/js/bundle.js
  client/dist/styles/bundle.css
  client/src/bundles/CheckForUpdates.js
  client/src/bundles/GridfieldDropdownFilter.js
  client/src/bundles/bundle.js
  client/src/styles/bundle.scss
  client/src/styles/sitesummary.scss
  composer.json
  css/sitesummary.css
  javascript/CheckForUpdates.js
  javascript/GridfieldDropdownFilter.js
  lang/en.yml
  package.json
  src/Forms/GridFieldDropdownFilter.php
  src/Forms/GridFieldRefreshButton.php
  src/Reports/SiteSummary.php
  templates/SiteSummary_VersionHeader.ss
  tests/Forms/GridFieldRefreshButtonTest.php
  webpack.config.js
  yarn.lock
Labels: affects/v4, change/minor
