Repository bringyourownideas/silverstripe-maintenance, pull requests merged in 2018-06, with the labels that each got.

#88 NEW Adding task segment
  src/Tasks/UpdatePackageInfoTask.php
Labels: affects/v4, change/minor

#94 FIX Set default return value for cache miss to false
  src/Util/SupportedAddonsLoader.php
Labels: affects/v4, change/patch

#92 API Move template into namespaced folder locations
  src/Model/Package.php
  src/Reports/SiteSummary.php
  templates/BringYourOwnIdeas/Maintenance/Model/Package/Summary.ss
  templates/BringYourOwnIdeas/Maintenance/Reports/SiteSummary/VersionHeader.ss
Labels: affects/v4, change/major

#95 Implementing job rescheduling for the queued job
  src/Forms/GridFieldRefreshButton.php
  src/Jobs/CheckForUpdatesJob.php
  tests/Forms/GridFieldRefreshButtonTest.php
  tests/Forms/GridFieldRefreshButtonTest.yml
Labels: affects/v3, change/minor

#97 NEW Move module info into React component with popover
  client/dist/js/bundle.js
  client/dist/styles/bundle.css
  client/src/bundles/bundle.js
  client/src/components/ModuleDetails/ModuleDetails.js
  client/src/components/ModuleDetails/ModuleDetails.scss
  client/src/legacy/entwine/CheckForUpdates.js
  client/src/legacy/entwine/GridfieldDropdownFilter.js
  client/src/legacy/entwine/SiteSummary.js
  client/src/styles/bundle.scss
  package.json
  src/Reports/SiteSummary.php
  templates/BringYourOwnIdeas/Maintenance/Model/Package/Summary.ss
  webpack.config.js
  yarn.lock
Labels: affects/v4, change/minor

#101 FIX Make table row click open popup, make trigger keyboard accessible
  client/dist/js/bundle.js
  client/dist/styles/bundle.css
  client/src/components/ModuleDetails/ModuleDetails.js
  client/src/components/ModuleDetails/ModuleDetails.scss
  client/src/legacy/entwine/SiteSummary.js
Labels: affects/v4, change/patch

#106 DOCS Add more information about security alerts to user guide
  docs/en/userguide/index.md
Labels: affects/v3, type/docs

#107 NEW Adding memory limit setting
  src/Tasks/UpdatePackageInfoTask.php
Labels: affects/v3, change/minor

#114 FIX Guzzle Client options can be configured by extensions
  src/Util/ApiLoader.php
Labels: affects/v4, change/patch

#115 FIX Guzzle Client options can be configured by extensions
  src/Util/SupportedAddonsLoader.php
Labels: affects/v3, change/patch
